# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_package\administratorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1138, 847)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(370, 10, 331, 111))
        font = QtGui.QFont()
        font.setFamily("Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers) # 表格不可编辑
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows) # 设置选中整行
        self.tableWidget.setGeometry(QtCore.QRect(200, 190, 361, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(730, 200, 181, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 350, 181, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(730, 500, 181, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 640, 181, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(950, 770, 151, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 770, 151, 61))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Administrator"))
        self.label.setText(_translate("Form", "Welcome,adiministrator"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "password"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_2.setText(_translate("Form", "Check"))
        self.pushButton_3.setText(_translate("Form", "Delete"))
        self.pushButton_4.setText(_translate("Form", "Modify"))
        self.pushButton_5.setText(_translate("Form", "Exit"))
        self.pushButton_6.setText(_translate("Form", "Back"))
