# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classify_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1574, 975)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 60, 441, 71))
        self.label.setObjectName("label")
        self.classificationsig = QtWidgets.QPushButton(Form)
        self.classificationsig.setGeometry(QtCore.QRect(210, 760, 241, 91))
        self.classificationsig.setObjectName("classificationsig")
        self.Output_classresult_2 = QtWidgets.QLineEdit(Form)
        self.Output_classresult_2.setGeometry(QtCore.QRect(372, 880, 113, 28))
        self.Output_classresult_2.setObjectName("Output_classresult_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 880, 171, 21))
        self.label_2.setObjectName("label_2")
        self.Inputpath = QtWidgets.QLineEdit(Form)
        self.Inputpath.setGeometry(QtCore.QRect(260, 240, 511, 28))
        self.Inputpath.setObjectName("Inputpath")
        self.pathbutton = QtWidgets.QPushButton(Form)
        self.pathbutton.setGeometry(QtCore.QRect(40, 230, 191, 40))
        self.pathbutton.setObjectName("pathbutton")
        self.showimage = QtWidgets.QLabel(Form)
        self.showimage.setGeometry(QtCore.QRect(210, 380, 521, 71))
        self.showimage.setObjectName("showimage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Steel Defects Classify</span></p></body></html>"))
        self.classificationsig.setText(_translate("Form", "Start Classify"))
        self.label_2.setText(_translate("Form", "Classify result:"))
        self.pathbutton.setText(_translate("Form", "Select the path"))
        self.showimage.setText(_translate("Form", "Here given the image that you want to classify"))
